ProyectoIzaje/WebIzaje/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebIzaje.Models;

namespace WebIzaje.Controllers
{
    public class InfoController : Controller
    {
        //
        // GET: /Info/

        [HttpGet]
        public ActionResult All(string id)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
            string item1 = string.Empty;
            string item2 = string.Empty;
            string item3 = string.Empty;
            string item4 = string.Empty;

            if (!string.IsNullOrEmpty(id) && id.Contains("item1") && id.Contains("item2") && id.Contains("item3") && id.Contains("item4"))
            {
                string[] item = id.Split(';');
                item1 = item[0].Split('=')[1];
                item2= item[1].Split('=')[1];
                item3 = item[2].Split('=')[1];
                item4 = item[3].Split('=')[1];
                string[] date_in = item3.Split('-');
                DateTime date_inicio = new DateTime(int.Parse(date_in[2]),int.Parse(date_in[1]),int.Parse(date_in[0]));
                string[] date_out = item4.Split('-');
                DateTime date_fin = new DateTime(int.Parse(date_out[2]), int.Parse(date_out[1]), int.Parse(date_out[0]));
                

                if (item1.Equals("all")) item1 = string.Empty;
                if (item2.Equals("all")) item2 = string.Empty;

                ViewBag.item1 = item1;
                ViewBag.item2 = item2;
                ViewBag.item3 = item3;
                ViewBag.item4 = item4;

                return View(Solicitud.obtenerTodas_info(item1.Trim(), item2.Trim(), date_inicio, date_fin));
            }

            ViewBag.item1 = item1;
            ViewBag.item2 = item2;
            ViewBag.item3 = item3;
            ViewBag.item4 = item4;

            return View(Solicitud.obtenerTodas_info(DateTime.Now));

            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public string GetTrabajadores(){
            string cadena = string.Empty;
            foreach (TrabajadorDatos x in new TrabajadorGet().AllDatos())
            {
                cadena += x.rut + " : " + x.nombre + " " + x.apellidoP + " " + x.apellidoM + ",";
            }
            cadena = cadena.TrimEnd(',');
            return cadena;
        }

        public string GetEquipos()
        {
            string cadena = string.Empty;
            foreach (DatosEquipo x in new conexion().obtener_lista_equipos())
            {
                
                cadena += x.tag + " : " + x.modelo + ",";
            }
            cadena = cadena.TrimEnd(',');
            return cadena;
        }
	}
}

ProyectoIzaje/WebIzaje/Controllers/SolicitudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebIzaje.Models;
using System.Web.Hosting;
using System.IO;
using Postal;

namespace WebIzaje.Controllers
{
    public class SolicitudController : Controller
    {        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult agregarSolicitud()
        {
            ViewData["gerencias"] = obtenerGerencias().ToArray();
            ViewData["criticidad"] = new conexion().obtenerCriticidad();
            return View();
        }
        public ActionResult editarSolicitud(string idSolicitud)
        {
            Solicitud dato = Solicitud.obtenerSolicitud(idSolicitud);

            ViewData["criticidad"] = new conexion().obtenerCriticidad();

            ViewData["turnoDia"] = "turno dia";
            ViewData["turnoNoche"] = "turno noche";

            ViewData["gerencias"] = obtenerGerencias().ToArray();
            ViewData["superintendencias"] = obtenerSuperintendencias(dato.gerencia).ToArray();
            ViewData["areas"] = obtenerAreas(dato.superintendencia).ToArray();
            ViewData["centrosDeCosto"] = obtenerCentroCosto(dato.area).ToArray();
            
            return View(dato);
        }
        public ActionResult verSolicitud(string idSolicitud)
        {
            Solicitud dato = Solicitud.obtenerSolicitud(idSolicitud);
            
            return View(dato);
        }
        public ActionResult planificarSolicitud(string idSolicitud)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                var dato = Solicitud.obtenerSolicitud(idSolicitud);

                ViewData["criticidad"] = new conexion().obtenerCriticidad();

                ViewData["turnoDia"] = "turno dia";
                ViewData["turnoNoche"] = "turno noche";

                ViewData["familiasEquipo"] = obtenerFamiliasEquipo();

                return View(dato);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult replanificarSolicitud(string idSolicitud)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                var dato = Solicitud.obtenerSolicitud(idSolicitud);

                ViewData["criticidad"] = new conexion().obtenerCriticidad();

                ViewData["turnoDia"] = "turno dia";
                ViewData["turnoNoche"] = "turno noche";

                ViewData["familiasEquipo"] = obtenerFamiliasEquipo();

                return View(dato);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult autorizarSolicitud(string idSolicitud)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("jefeArea")))
            {
                var dato = Solicitud.obtenerSolicitud(idSolicitud);

                //string fecha= dato.inicio.Date.ToString().Split(' ')[0];
                ViewData["fecha"] = dato.inicio.Date;

                ViewData["medianamentecritica"] = "Medianamiente crítica";
                ViewData["critica"] = "Crítica";

                ViewData["turnoDia"] = "Día";
                ViewData["turnoNoche"] = "Noche";

                return View(dato);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult finalizarSolicitud(string idSolicitud)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                var dato = Solicitud.obtenerSolicitud(idSolicitud);

                //string fecha= dato.inicio.Date.ToString().Split(' ')[0];
                ViewData["fecha"] = dato.inicio.Date;
                
                ViewData["medianamentecritica"] = "Medianamiente crítica";
                ViewData["critica"] = "Crítica";

                ViewData["turnoDia"] = "turno dia";
                ViewData["turnoNoche"] = "turno noche";

                DatosEquipo equipo1= new EquipoSelect().obtener_equipos(dato.idEquipo1);
                equipo1.datos_nocautivo = new EquipoNoCautivoSelect().obtener_Nocautivo(equipo1.tipo_equipo);
                ViewData["uf1"] = equipo1.datos_nocautivo.costo_hora;
                if (!dato.idEquipo2.Equals("--"))
                {
                    DatosEquipo equipo2 = new EquipoSelect().obtener_equipos(dato.idEquipo2);
                    equipo2.datos_nocautivo = new EquipoNoCautivoSelect().obtener_Nocautivo(equipo2.tipo_equipo);
                    ViewData["uf2"] = equipo2.datos_nocautivo.costo_hora;
                }
                else 
                {
                    ViewData["uf2"] = 0;
                }

                //Se obtienen los días que duró el servicio y se envía esta información
                ViewData["dias"] = obtenerDias(dato.inicioCorregido, dato.finCorregido);

                return View(dato);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ActionResult corregirDatos(string idSolicitud)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                var dato = Solicitud.obtenerSolicitud(idSolicitud);

                ViewData["criticidad"] = new conexion().obtenerCriticidad();

                ViewData["turnoDia"] = "turno dia";
                ViewData["turnoNoche"] = "turno noche";

                DatosEquipo equipo1=new EquipoSelect().obtener_equipos(dato.idEquipo1);

                ViewData["familiasEquipo"] = obtenerFamiliasEquipo();
                ViewData["familiaEquipo1"] = equipo1.familia_equipo;
                
                string tiposEquipo1 = new WebIzaje.Controllers.EquipoController().rescatar_datos_tipoequipo(equipo1.familia_equipo);
                string[] tiposEquipo1Arr = tiposEquipo1.Split(',');
                List<string> tiposEquipo1List = new List<string>();
                for (int i = 0; i < tiposEquipo1Arr.Length; i++) 
                {
                    tiposEquipo1List.Add(tiposEquipo1Arr[i]);
                }

                ViewData["tiposEquipo1"] = tiposEquipo1List;
                ViewData["tipoEquipo1"] = equipo1.tipo_equipo;

                List<string> equipos1 = new conexion().obtenerEquiposPorTipo(equipo1.tipo_equipo);
                List<string> equipos1Format = new List<string>();
                for (int i = 0; i < equipos1.Count; i++) 
                {
                    DatosEquipo temp = new EquipoSelect().obtener_equipos(equipos1[i]);
                    equipos1Format.Add(temp.tag + "/" + temp.marca + " " + temp.modelo);
                }
                ViewData["equipos1"] = equipos1Format;

                List<string> operadores1 = new conexion().obtenerOperadoresPorTag(equipo1.tag);
                List<string> operadores1Format = new List<string>();
                for (int i = 0; i < operadores1.Count; i++)
                {
                    TrabajadorDatos temp = new TrabajadorGet().trabajador(operadores1[i]);
                    operadores1Format.Add(temp.rut + "/" + temp.nombre + " " + temp.apellidoP);
                }
                ViewData["operadores1"] = operadores1Format;

                List<string> riggers1 = new conexion().obtenerRiggersPorTag(equipo1.tag);
                List<string> riggers1Format = new List<string>();
                for (int i = 0; i < riggers1.Count; i++)
                {
                    TrabajadorDatos temp = new TrabajadorGet().trabajador(riggers1[i]);
                    riggers1Format.Add(temp.rut + "/" + temp.nombre + " " + temp.apellidoP);
                }
                ViewData["riggers1"] = riggers1Format;


                if (!dato.idEquipo2.Equals("--")) 
                {
                    DatosEquipo equipo2 = new EquipoSelect().obtener_equipos(dato.idEquipo2);

                    ViewData["familiaEquipo2"] = equipo2.familia_equipo;

                    string tiposEquipo2 = new WebIzaje.Controllers.EquipoController().rescatar_datos_tipoequipo(equipo2.familia_equipo);
                    string[] tiposEquipo2Arr = tiposEquipo2.Split(',');
                    List<string> tiposEquipo2List = new List<string>();
                    for (int i = 0; i < tiposEquipo2Arr.Length; i++)
                    {
                        tiposEquipo2List.Add(tiposEquipo2Arr[i]);
                    }

                    ViewData["tiposEquipo2"] = tiposEquipo2List;
                    ViewData["tipoEquipo2"] = equipo2.tipo_equipo;

                    List<string> equipos2 = new conexion().obtenerEquiposPorTipo(equipo2.tipo_equipo);
                    List<string> equipos2Format = new List<string>();
                    for (int i = 0; i < equipos2.Count; i++)
                    {
                        DatosEquipo temp = new EquipoSelect().obtener_equipos(equipos2[i]);
                        equipos2Format.Add(temp.tag + "/" + temp.marca + " " + temp.modelo);
                    }
                    ViewData["equipos2"] = equipos2Format;

                    List<string> operadores2 = new conexion().obtenerOperadoresPorTag(equipo2.tag);
                    List<string> operadores2Format = new List<string>();
                    for (int i = 0; i < operadores2.Count; i++)
                    {
                        TrabajadorDatos temp = new TrabajadorGet().trabajador(operadores2[i]);
                        operadores2Format.Add(temp.rut + "/" + temp.nombre + " " + temp.apellidoP);
                    }

ProyectoIzaje/WebIzaje/Views/Info/All.cshtml
@model IEnumerable<WebIzaje.Models.Solicitud>
@{
    ViewBag.Title = "Index";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 10);
}
<div class="container">
    <div class="page-header">
        <h2>
            Servicios
            <button type="button" class="btn btn-default btn-group pull-right" data-toggle="modal" data-target="#myModal"><i class="glyphicon glyphicon-filter"></i>&nbsp;Filtro</button>
        </h2>
    </div>

    <div class="table-responsive">

        @grid.GetHtml(
            columns: grid.Columns(

        grid.Column("idSolicitud",
                 header: string.Format("Id {0}", grid.SortColumn == "idSolicitud" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            
            <span class="badge">@item.idSolicitud</span>
            </text>),

        grid.Column("area",
                 header: string.Format("Área {0}", grid.SortColumn == "area" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            <span>@item.area</span>
            </text>),

        grid.Column("centroCosto",
                 header: string.Format("Centro de Costo {0}", grid.SortColumn == "centroCosto" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            <span>@item.centroCosto</span>
            </text>),

        grid.Column("inicioCorregido",
                 header: string.Format("Inicio {0}", grid.SortColumn == "inicioCorregido" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            <span>@item.inicioCorregido</span>
            </text>),

        grid.Column("finCorregido",
                 header: string.Format("Fin {0}", grid.SortColumn == "finCorregido" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            <span>@item.finCorregido</span>
            </text>),

        grid.Column("idEquipo1",
                 header: string.Format("Equipos {0}", grid.SortColumn == "idEquipo1" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            <span>@item.idEquipo1 - @item.idEquipo2</span>
            </text>),

        grid.Column("idOperador1",
                 header: string.Format("Operadores {0}", grid.SortColumn == "idOperador1" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            <span>@item.idOperador1 - @item.idOperador2</span>
            </text>),

        grid.Column("idRigger1",
                 header: string.Format("Riggers {0}", grid.SortColumn == "idRigger1" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
            <span>@item.idRigger1 - @item.idRigger2</span>
            </text>),

        grid.Column("",
            header: "",
            format: @<text>
                <a href="@Url.Action("verSolicitud", "Solicitud", new { idSolicitud = item.idSolicitud })" title="Ver Solicitud"><i class='glyphicon glyphicon-edit text-primary'></i></a>
            </text>)
         ), tableStyle: "table table-hover", footerStyle: "pagination")

    </div>
    <hr />
    @if (string.IsNullOrEmpty(ViewBag.item1))
    {
        <span class="label label-warning">E: Todos</span> 
    }else {<span class="label label-warning">T: @ViewBag.item1</span> 
    }
                                                   
    @if (string.IsNullOrEmpty(ViewBag.item2))
    {
        <span class="label label-warning">T: Todos</span> 
    }
    else {<span class="label label-warning">T: @ViewBag.item2</span> 
    }

    @if (string.IsNullOrEmpty(ViewBag.item3))
    {
        <span class="label label-warning">F.I: 01-@DateTime.Now.Month-@DateTime.Now.Year</span> 
    }else {<span class="label label-warning">F.I: @ViewBag.item3</span> 
    }

    @if (string.IsNullOrEmpty(ViewBag.item4))
    {
        DateTime mes = DateTime.Now.AddMonths(1);
        <span class="label label-warning">F.T: 01-@mes.Month-@mes.Year</span> 
    }else {<span class="label label-warning">F.T: @ViewBag.item4</span>  
    }


</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><i class="glyphicon glyphicon-filter"></i>&nbsp;Filtrar</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-muted">Equipo:</label>
                                <select class="form-control" id="equipos" name="_equipo">
                                </select>
                                <input type="hidden" id="equipo" value="@ViewBag.item1" />
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-muted">Trabajador:</label>
                                <select class="form-control" id="trabajadores" name="_trabajador">
                                </select>
                                <input type="hidden" id="trabajador" value="@ViewBag.item2" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-muted">Fecha Inicio:</label>
                                @if (string.IsNullOrEmpty(ViewBag.item3))
                                {
                                    DateTime date = DateTime.Now;
                                   <input type="text" class="form-control" id="fecha_inicio" name="_fecha_inicio" value="01+'/'+@date.Month+'/'+@date.Year" data-date-format="DD/MM/YYYY" pattern="\d{2}\/\d{2}\/\d{4}" placeholder="dd/mm/aaaa" placeholder="Inicio" /> 
                                }
                                else
                                {
                                    <input type="text" class="form-control" id="fecha_inicio" name="_fecha_inicio" value="@ViewBag.item3" data-date-format="DD/MM/YYYY" pattern="\d{2}\/\d{2}\/\d{4}" placeholder="dd/mm/aaaa" placeholder="Inicio" />
                                }
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-muted">Fecha Término:</label>
                                @if (string.IsNullOrEmpty(ViewBag.item3))
                                {
                                    DateTime date = DateTime.Now.AddMonths(1);
                                    <input type="text" class="form-control" id="fecha_termino" name="_fecha_termino" value="01+'/'+@date.Month+'/'+@date.Year" data-date-format="DD/MM/YYYY" pattern="\d{2}\/\d{2}\/\d{4}" placeholder="dd/mm/aaaa" placeholder="Fin" />
                                }
                                else
                                {
                                    <input type="text" class="form-control" id="fecha_termino" name="_fecha_termino" value="@ViewBag.item4" data-date-format="DD/MM/YYYY" pattern="\d{2}\/\d{2}\/\d{4}" placeholder="dd/mm/aaaa" placeholder="Fin" />
                                }
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i>&nbsp;Cerrar</button>
                        <button type="button" class="btn btn-primary" id="btn-info"><i class="glyphicon glyphicon-check"></i>&nbsp;Aceptar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">



    $(function () {
        $('#fecha_inicio').datetimepicker({
            viewMode: 'days',
            format: 'DD/MM/YYYY'
        });
        $('#fecha_termino').datetimepicker({
            viewMode: 'days',
            format: 'DD/MM/YYYY'
        });
        $("#fecha_inicio").on("dp.change", function (e) {
            $('#fecha_termino').data("DateTimePicker").minDate(e.date);
        });
        $("#fecha_termino").on("dp.change", function (e) {
            $('#fecha_inicio').data("DateTimePicker").maxDate(e.date);
        });
    });


    $.ajax({
        url: "@Url.Action("GetEquipos","Info")",
        success: function (items) {
            $("#equipos").html('');
            $("#equipos").append("<option value='all'>-- Equipos --</option>");

            if (items.length > 0) {
                var item = items.split(',');
                var itemx = $('#equipo').val().trim();

                for (i = 0; i < item.length; i++) {
                    
                    if (itemx == item[i].split(':')[0].trim()) {
                        $("#equipos").append("<option value='" + item[i] + "' selected>" + item[i] + "</option>");
                    } else {
                        $("#equipos").append("<option value='" + item[i] + "'>" + item[i] + "</option>");
                    }
                }
            }
        }
    });



    $.ajax({
        url: "@Url.Action("GetTrabajadores","Info")",
        success: function (items) {
            $("#trabajadores").html('');
            $("#trabajadores").append("<option value='all'>-- Trabajador --</option>");

            if (items.length > 0) {
                var item = items.split(',');
                var itemx = $('#trabajador').val().trim();
                for (i = 0; i < item.length; i++) {
                    
                    if (itemx == item[i].split(':')[0].trim()) {
                        $("#trabajadores").append("<option value='" + item[i] + "' selected>" + item[i] + "</option>");
                    }else{
                        $("#trabajadores").append("<option value='" + item[i] + "'>" + item[i] + "</option>");
                    }

                }
            }
        }
    });

    $('#btn-info').click(function () {
        var equipo = $('#equipos').val();
        if (equipo != "all") {
            equipo = equipo.split(':')[0];
        }
        var trabajador = $('#trabajadores').val();
        if (trabajador != "all") {
            trabajador = trabajador.split(':')[0];
        }
        var fecha_in = $('#fecha_inicio').val().replace("/", "-");
        fecha_in = fecha_in.replace("/","-");

        var fecha_out = $('#fecha_termino').val().replace("/","-");
        fecha_out = fecha_out.replace("/","-");

        window.location = "/Info/All/"+ "item1=" + equipo + ";item2=" + trabajador + ";item3=" + fecha_in + ";item4=" + fecha_out;
    })


    </script>
}