ProyectoIzaje/WebIzaje/Models/Equipo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using WebIzaje.Code;

namespace WebIzaje.Models
{

        public class DatosEquipo
        {
            public string familia_equipo { get; set; }
            public string tipo_equipo { get; set; }
            public string marca { get; set; }
            public string modelo { get; set; }
            public string año_fabricacion { get; set; }
            public string capacidad { get; set; }
            public string estado { get; set; }
            public string empresa_propietaria { get; set; }
            public string tag { get; set; }
            public List<EquipoCertificados> datos_certificados{get;set;}
            public string cautivo { get; set; }
            public string nocautivo { get; set; }
            public EquipoCautivo datos_cautivo { get; set; }
            public EquipoNoCautivo datos_nocautivo { get; set; }
            public string fecha_ingreso_faena { get; set; }
            public string odometro { get; set; }
            public string horas_horometro { get; set; }
            public string url_imagen { get; set; }
        }
       
         public class EquipoCautivo
         {
             public string tag_equipo{get;set;}
             public string costo_fijo { get; set; }
             public string area_trabajo { get; set; }
         
         }

         #region seleccion y insercion equipo cautivo
         public class EquipoCautivoInsert
         {
             public void saveEquipocautivo(EquipoCautivo dato_cautivo)
             {
                 new conexion().guardar_Equipocautivo(dato_cautivo);
             }
             public void updateEquipocautivo(EquipoCautivo dato_cautivo)
             {
                 new conexion().update_Equipocautivo(dato_cautivo);
             }
             
         }
         public class EquipoCautivoSelect
         {
             public EquipoCautivo obtener_cautivo(string tag)
             {
                 EquipoCautivo datos=new EquipoCautivo();
                 datos=new conexion().obtener_datos_cautivo(tag);
                 return datos;
             }
             
         }
        #endregion
         public class EquipoNoCautivo
         {
             public string tag_equipo { get; set; }
             public string tipo_equipo { get; set; }
             public string costo_hora { get; set; }
             public string costo_hora_extra { get; set; }
             public string minimo_garantizado { get; set; }
         
         }

         #region seleccion  en tabla tipoequipo de equipos nocautivos
         public class EquipoNoCautivoSelect
         {
             public EquipoNoCautivo obtener_Nocautivo(string tipo_equipo)
             {
                 EquipoNoCautivo datos = new EquipoNoCautivo();
                 datos = new conexion().obtener_datos_Nocautivo(tipo_equipo);
                 return datos;
             }
             
         }
         
        #endregion
         #region seleccion y inserccion de certificados
         public class EquipoCertificados
         {
             public string tag_equipo { get; set; }
             public string fecha_vencimiento { get; set; }
             public string nombre_certificado { get; set; }
             public string url { get; set; }

         }
         public class EquipoCertificadosInsert
         {
             public bool saveCertificados(EquipoCertificados lista_certificados)
             {
                 return new conexion().guardar_certificados(lista_certificados);

             }
            
         }
         public class EquipoCerticadosDelete
         {
             public bool delete_certificados(string tag)
             {
                 return new conexion().eliminar_certificados(tag);
             }
            
         }
         public class EquipoDelete
         {
             public bool delete_equipo(string tag)
             {
               return  new conexion().eliminar_equipo(tag);
             }
            
         }
         public class EquipoCertificadoSelect
         {
             public List<EquipoCertificados> lista_certificados(string tag)
             {
                 List<EquipoCertificados> lista_datos = new List<EquipoCertificados>();
                 lista_datos = new conexion().obtener_certificados(tag);
                 return lista_datos;
             }
           
         }
         #endregion
         public class EquipoInsert
         {

             public bool savedatosequipo(DatosEquipo equipo)
             {
                 return new conexion().guardar_datosequipo(equipo);
             }
           

         }
         public class EquipoSelect
         {
             public DatosEquipo obtener_equipos(string tag)
             {
                 DatosEquipo datos= new DatosEquipo();
                 datos=new conexion().obtener_datos_equipo(tag);
                 return datos;
             }
             


         }
         public class ListaEquipos
         {
             #region metodo para mostrar lista de equipos
             public List<DatosEquipo> mostrar_lista_datos()
             {
                 // se consulta en la bd por todos los equipos disponibles
                 List<DatosEquipo> lista_datos = new List<DatosEquipo>();
                 lista_datos = new conexion().obtener_lista_equipos();
                 return lista_datos;
             }
             
             #endregion
         }         
        public class ObtenerDatosTablasFijas
        {

            #region datos que se obtien de tablas sin pasar parametros
            public string[] obtener_datos_familia()
            {
                return new conexion().datos_familia();
            }
            
             public string[] obtener_datos_marca()
            {
                return new conexion().datos_marca();
            }
             
             public string[] obtener_datos_empresa()
             {
                 return new conexion().datos_empresa();
             }
            
             public string[] obtener_datos_area()
             {
                 return new conexion().datos_area();
             }
             
            #endregion

             #region datos que se obtiene pasando parmetros
             public string[] obtener_datos_tipo_equipo(string familia)
             {
                 return new conexion().datos_tipo_equipo(familia);
             }
             
             public string[] obtener_datos_modelo(string marca, string tipo)
             {
                 return new conexion().datos_modelo(marca,tipo);
             }

             public string[] obtener_datos_marcas(string tipo)
             {
                 return new conexion().datos_marcas(tipo);
             }
            
             #endregion
        }
        public class MetodosReportesEquipo
        {
            public List<DatosEquipo> mostrar_lista_datos_por_fecha(string fechaingreso)
            {
                // se consulta en la bd por todos los equipos disponibles
                List<DatosEquipo> lista_datos = new List<DatosEquipo>();
                lista_datos = new conexion().obtener_equipos_por_fecha(fechaingreso);
                return lista_datos;
            }
        }
}
    

ProyectoIzaje/WebIzaje/Controllers/EquipoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebIzaje.Code;
using WebIzaje.Models;
using System.Text;
using System.Xml;
using System.Web.UI;

namespace WebIzaje.Controllers
{
    public class EquipoController : Controller
    {
        //
        // GET: /Equipo/
        // para validar errores eliminacion y guardados
        static int flag = -1;
       [HttpGet]
        public ActionResult Eliminar(string eliminar)
        {
            if ((Session["rol"] != null) && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                EquipoDelete eliminar_equipo = new EquipoDelete();
                EquipoCerticadosDelete eliminar_certificados = new EquipoCerticadosDelete();
                bool respuesta_equipo = eliminar_equipo.delete_equipo(eliminar);
                bool respuesta_certificado = eliminar_certificados.delete_certificados(eliminar);
                bool respuesta_directorio = deleteDiretory(eliminar);
                if ((respuesta_equipo == true) && (respuesta_certificado == true) && (respuesta_directorio == true))
                {
                    flag = 1;
                }
                else
                {
                    flag = 0;
                }
                return RedirectToAction("Todos");
            }
            else
            { return RedirectToAction("Index", "Home"); }
        }
        [HttpGet]
        public ActionResult Todos()
        {
            if ((Session["rol"] != null) && (Session["rol"].Equals("admin") || (Session["rol"].Equals("izaje"))))
            {
                ViewBag.success = flag;
                flag = -1;
                ListaEquipos datos = new ListaEquipos();
                return View(datos.mostrar_lista_datos());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public ActionResult Nuevo()
        {
            if ( Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                // consultas a la bd para obtener los datos estaticos de las tablas
                ObtenerDatosTablasFijas datos_tablas_fijas = new ObtenerDatosTablasFijas();
                string[] estado = new string[] { "Disponible", "NoDisponible" };
                ViewData["familia_equipo"] = datos_tablas_fijas.obtener_datos_familia();
                //ViewData["marca"] = datos_tablas_fijas.obtener_datos_marca();
                ViewData["empresa"] = datos_tablas_fijas.obtener_datos_empresa();
                ViewData["area"] = datos_tablas_fijas.obtener_datos_area(); ;
                ViewData["estado"] = estado;
                return View();
            }
            else
            {
               return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public ActionResult Editar(string tag)
        {
            if ((Session["rol"] != null) && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                // datos a obtener de la base de datos
                ObtenerDatosTablasFijas datos_tablas_fijas = new ObtenerDatosTablasFijas();
                string[] estado = new string[] { "Disponible", "NoDisponible" };
                ViewData["familia_equipo"] = datos_tablas_fijas.obtener_datos_familia();
                //ViewData["marca"] = datos_tablas_fijas.obtener_datos_marca();
                ViewData["empresa"] = datos_tablas_fijas.obtener_datos_empresa();
                ViewData["area"] = datos_tablas_fijas.obtener_datos_area(); ;
                ViewData["estado"] = estado;
                DatosEquipo datos_equipo = new DatosEquipo();
                EquipoSelect seleccionar_equipo = new EquipoSelect();
                datos_equipo = seleccionar_equipo.obtener_equipos(tag);
                if (datos_equipo.nocautivo.Equals("True"))
                {
                    EquipoNoCautivoSelect seleccionar_nocautivo = new EquipoNoCautivoSelect();
                    EquipoNoCautivo dato = new EquipoNoCautivo();
                    dato = seleccionar_nocautivo.obtener_Nocautivo(datos_equipo.tipo_equipo);
                    datos_equipo.datos_nocautivo = dato;
                }
                else
                {
                    EquipoCautivoSelect seleccionar_cautivo = new EquipoCautivoSelect();
                    EquipoCautivo dato = new EquipoCautivo();
                    dato = seleccionar_cautivo.obtener_cautivo(tag);
                    datos_equipo.datos_cautivo = dato;
                }
                EquipoCertificadoSelect seleccionar_certificados = new EquipoCertificadoSelect();
                List<EquipoCertificados> dato_certificado = new List<EquipoCertificados>();
                dato_certificado = seleccionar_certificados.lista_certificados(tag);
                datos_equipo.datos_certificados = dato_certificado;

                return View(datos_equipo);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
         }

      
       
        [HttpPost]
        // el httppostedfilebase permite pasar los documentos o imagenes con el unico requerimiento de que el name sea el mismo qe la variable de entrada
        public ActionResult guardarNuevo(FormCollection datos_form, HttpPostedFileBase imagen, IEnumerable<HttpPostedFileBase> file_)
        {
            // insertar estos datos en la Bd
            DatosEquipo datos_equipo = new DatosEquipo();
            EquipoInsert insertar_equipo = new EquipoInsert();
            EquipoCertificadosInsert insertar_certificado = new EquipoCertificadosInsert();
            
                
            // se crea la carpeta con el tag ingresado
                if (this.createFolder(datos_form["tag"]))
                {
                    //insertar Datos en la bd
                    datos_equipo=saveDatos(datos_form,imagen,"save");
                   bool retorno_guardar= insertar_equipo.savedatosequipo(datos_equipo);
                        //inserta certificados en bd
                    saveCertificados(datos_form, file_);
                    if (retorno_guardar == true)
                    {
                        flag = 1;
                    }
                    else
                    {
                        flag = 0;
                    }
                }

                return RedirectToAction("Todos");
        }
        [HttpPost]
        public ActionResult guardarEditar(FormCollection form, HttpPostedFileBase imagen, IEnumerable<HttpPostedFileBase> file_)
        {
            flag = 1;
            string id = form["tag"];//new
            string id_old = form["tagOld"];//old
            
            //elimina todos los certificados que se hallan eliminado en el formulario
            if (!form["clear_c"].Equals(""))
            {
                string[] clear_c = form["clear_c"].TrimEnd(';').Split(';');
                foreach (string x in clear_c)
                {
                    this.deleteFile(x);
                }
            }
            //si se realiza el cambio de nombre del directory
            if (renameFolder(id, id_old))
            {
                //update datos
                EquipoDelete eliminar_equipo = new EquipoDelete();
                if (eliminar_equipo.delete_equipo(id_old))
                {
                    EquipoInsert insertar_nuevo_equipo = new EquipoInsert();
                    if (!insertar_nuevo_equipo.savedatosequipo(saveDatos(form, imagen,"update"))) flag = 0;
                }
                else flag = 0;

                //delete BD
                EquipoCerticadosDelete eliminar_certificados = new EquipoCerticadosDelete();
                if (eliminar_certificados.delete_certificados(id_old))
                {
                    //Update Certificados
                    if (!saveCertificados(form, file_)) flag = 0;
                }
                else flag = 0;
            }
            else flag = 0;

            return RedirectToAction("Todos");
        }

        private DatosEquipo saveDatos(FormCollection datos_form, HttpPostedFileBase imagen,string tipo_accion)
        {
            string tag = datos_form["tag"];

            DatosEquipo datos_equipo = new DatosEquipo();
            EquipoCautivo equipocautivo = new EquipoCautivo();
            EquipoCautivoInsert equipocautivoInsert = new EquipoCautivoInsert();

            datos_equipo.familia_equipo = datos_form["familiaE"];
            datos_equipo.tipo_equipo = datos_form["tipoE"];
            datos_equipo.marca = datos_form["marcaE"];
            datos_equipo.modelo = datos_form["modeloE"];
            datos_equipo.año_fabricacion = datos_form["añof"];
            datos_equipo.capacidad = datos_form["capacidadE"];
            datos_equipo.estado = datos_form["EstadoE"];
            datos_equipo.empresa_propietaria = datos_form["empresaPE"];
            datos_equipo.tag = datos_form["tag"];

            if (datos_form["seleccion"].Equals("ECautivo"))
            {
                datos_equipo.cautivo = "True";
                datos_equipo.nocautivo = "False";
                equipocautivo.tag_equipo = datos_form["tag"];
                equipocautivo.area_trabajo = datos_form["areaT"];
                equipocautivo.costo_fijo = datos_form["costoFijo"];
                
                    equipocautivoInsert.saveEquipocautivo(equipocautivo);
                
            }
            else
            {
                datos_equipo.nocautivo = "True";
                datos_equipo.cautivo = "False";
            }
            string[] fecha_ingreso = datos_form["fechaIngreso"].Split('/');

            datos_equipo.fecha_ingreso_faena = fecha_ingreso[2] + "-" + fecha_ingreso[1] + "-" + fecha_ingreso[0];

ProyectoIzaje/WebIzaje/Views/Equipo/Todos.cshtml
@model IEnumerable<WebIzaje.Models.DatosEquipo>
@{
    ViewBag.Title = "Equipos";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 10);
}


    <div class="container">

    @if (ViewBag.success == 0)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <strong><i class="glyphicon glyphicon-remove-circle text-danger"></i></strong>&nbsp;No se pudieron realizar los cambios!.
        </div>
    }
    @if (ViewBag.success == 1)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <strong><i class="glyphicon glyphicon-ok-circle text-success"></i></strong>&nbsp;Cambios realizados con exito!.
        </div>
    }
    @if (ViewBag.success == 2)
    {
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <strong><i class="glyphicon glyphicon-info-sign text-warning"></i></strong>&nbsp;Tag ingresado, ya existe!.
        </div>
    }

    <div class="page-header">
        <h2 class="text-center">Equipos</h2>
    </div><!-- cierre de page header-->

    <div class="table-responsive">
        <table class="table table-hover">

            @grid.GetHtml(
            columns: grid.Columns(
            
        grid.Column("tag",
                 header: string.Format("Tag {0}", grid.SortColumn == "tag" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
                    <span class="badge">@item.tag</span>
            </text>),

        grid.Column("familia_equipo",
            header: string.Format("Familia {0}", grid.SortColumn == "familia_equipo" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("tipo_equipo",
            header: string.Format("Tipo {0}", grid.SortColumn == "tipo_equipo" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("modelo",
            header: string.Format("Modelo {0}", grid.SortColumn == "modelo" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("año_fabricacion",
            header: string.Format("Año {0}", grid.SortColumn == "año_fabricacion" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("capacidad",
            header: string.Format("Capacidad {0}", grid.SortColumn == "capacidad" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("",
            header: "",
            format: @<text>
                <a href="@Url.Action("Editar", "Equipo", new { tag = @item.tag })" title="Editar"><i class='glyphicon glyphicon-edit text-primary'></i></a>
                &emsp;
                <a href="#" data-toggle="modal" data-target="#myModal" onclick="funcionDelete('@item.tag','@item.familia_equipo','@item.tipo_equipo')" title="Eliminar"><i class='glyphicon glyphicon-trash text-danger'></i></a>
            </text>)
        ), tableStyle: "table table-hover", footerStyle: "pagination")

        </div>
        <hr />
        <a href="@Url.Action("Nuevo", "Equipo")" type="button" class="btn btn-default"><i class="glyphicon glyphicon-plus-sign text-success"></i>&nbsp;Nuevo</a>


            <!--Modal-->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel">¿Eliminar Registro?</h4>
                        </div>
                        <div class="modal-body">
                            <h5 class="text-center" id="text-modal"></h5>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i>Cancelar</button>
                            <a href="" type="button" id="btn_delete" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i>Eliminar</a>
                        </div>
                    </div>
                </div>
            </div>

    </div><!-- cierre container-->

<!--CSS StickyFooter-->
<link rel="stylesheet" href="~/Content/bootstrap-stickyfooter.css">
<div class="footer">
    <footer>
        <h5 class="text-muted text-center">
            &copy; <strong>MINDgl</strong> <br />
            <i class="glyphicon glyphicon-map-marker text-muted"></i>&ensp;La Serena, Chile - @DateTime.Now.Year
        </h5>
    </footer>
</div>

    @section scripts{
        <script type="text/javascript">

            function funcionDelete(tag, familia, tipo) {
                $("#text-modal").html("");
                var cadena = "@Url.Action("Eliminar", "Equipo", new { eliminar = "tag"})";
                cadena = cadena.replace("tag", tag);
                $("#btn_delete").attr("href", cadena);
                $("#text-modal").append("¿Estás seguro de que deseas eliminar <strong>" + tag + "</strong> de Equipos?");
            }
        </script>
    }