ProyectoIzaje/WebIzaje/Controllers/TrabajadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebIzaje.Models;
using WebIzaje.Code;
using System.IO;
using WebIzaje.Controllers;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.Web.Hosting;


namespace WebIzaje.Controllers
{
    public class TrabajadorController : Controller
    {
        //
        // GET: /Trabajador/
        static int flag = -1;

        [HttpGet]
        public ActionResult Nuevo()
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                flag = -1;
                return View();
                
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        [HttpGet]
        public ActionResult Editar(string id)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                flag = -1;

                if (!string.IsNullOrEmpty(id))
                {
                    //recuperar datos con id{rut}
                    TrabajadorGet getTrabajador = new TrabajadorGet();
                    TrabajadorDatos tdato = getTrabajador.trabajador(id);
                    if (tdato.nombre != null)
                    {
                        return View(tdato);
                    }
                }
                return RedirectToAction("Todos");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public ActionResult Todos()
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                //recuperar all trabajadores
                TrabajadorGet tget = new TrabajadorGet();
                List<TrabajadorDatos> tdatos = tget.AllDatos();

                ViewBag.success = flag;
                flag = -1;
                return View(tdatos);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        
        [HttpPost]
        public ActionResult Guardar(FormCollection form, HttpPostedFileBase imagen, IEnumerable<HttpPostedFileBase> lnew_file, IEnumerable<HttpPostedFileBase> cnew_file, IEnumerable<HttpPostedFileBase> enew_file)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                flag = 1;
                string id = form["rut"];
                //si no existe el ID
                if (!new TrabajadorGet().existRut(id))
                {
                    //si se crea el directorio
                    if (this.createFolder(id))
                    {
                        //insertar Datos
                        if (new TrabajadorInsert().datos(this.saveDatos(form, imagen)))
                        {
                            //insertar licencias
                            foreach (TrabajadorLicencias item in saveLicencias(form, lnew_file))
                            {
                                if (!new TrabajadorInsert().licencias(item)) flag = 0;
                            }
                            //insertar certificados
                            foreach (TrabajadorCertificados item in saveCertificados(form, cnew_file))
                            {
                                if (!new TrabajadorInsert().certificados(item)) flag = 0;
                            }

                            //insertar equipos
                            foreach (TrabajadorEquipos item in saveEquipos(form, enew_file))
                            {
                                if (!new TrabajadorInsert().equipos(item)) flag = 0;
                            }

                            if (flag == 0)
                            {
                                this.Delete(id);
                            }
                        }
                        else { flag = 0; }
                    }
                    else { flag = 0; }
                }
                else { flag = 2; }//Si ya existe el Rut 

                return RedirectToAction("Todos");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        
        [HttpPost]
        public ActionResult GuardarEditar(FormCollection form, HttpPostedFileBase imagen, IEnumerable<HttpPostedFileBase> lnew_file, IEnumerable<HttpPostedFileBase> cnew_file, IEnumerable<HttpPostedFileBase> enew_file)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                flag = 1;
                string id = form["rut"];//new
                string id_old = form["rutOld"];//old

                bool existId = false;
                //si existen diferencias de ID
                if (diff(id, id_old))
                {
                    //verificar existencia de ID
                    existId = new TrabajadorGet().existRut(id);
                }

                if (!existId)
                {
                    //Delete Licencia
                    if (!string.IsNullOrEmpty(form["clear_l"]))
                    {
                        string[] clear_l = form["clear_l"].TrimEnd(';').Split(';');
                        //eliminar los files
                        foreach (string x in clear_l)
                        {
                            this.deleteFile(x);
                        }
                    }

                    //Delete Certificados
                    if (!string.IsNullOrEmpty(form["clear_c"]))
                    {
                        string[] clear_c = form["clear_c"].TrimEnd(';').Split(';');
                        foreach (string x in clear_c)
                        {
                            this.deleteFile(x);
                        }
                    }

                    //Delete Equipos
                    if (!string.IsNullOrEmpty(form["clear_e"]))
                    {
                        string[] clear_e = form["clear_e"].TrimEnd(';').Split(';');
                        foreach (string x in clear_e)
                        {
                            this.deleteFile(x);
                        }
                    }

                    //si se realiza el cambio de nombre del directory
                    if (renameFolder(id, id_old))
                    {
                        //update datos
                        if (new TrabajadorDelete().datos(id_old))
                        {
                            if (new TrabajadorInsert().datos(saveDatos(form, imagen)))
                            {
                                //delete BD
                                if (new TrabajadorDelete().licencias(id_old))
                                {
                                    //Update Licencias
                                    foreach (TrabajadorLicencias licencia in saveLicencias(form, lnew_file))
                                    {
                                        if (!new TrabajadorInsert().licencias(licencia)) flag = 0;
                                    }
                                }
                                else flag = 0;

                                //delete BD
                                if (new TrabajadorDelete().certificados(id_old))
                                {
                                    //Update Certificados
                                    foreach (TrabajadorCertificados certificado in saveCertificados(form, cnew_file))
                                    {
                                        if (!new TrabajadorInsert().certificados(certificado)) flag = 0;
                                    }
                                }
                                else flag = 0;

                                //delete BD
                                if (new TrabajadorDelete().equipos(id_old))
                                {
                                    //Update Equipos
                                    foreach (TrabajadorEquipos equipo in saveEquipos(form, enew_file))
                                    {
                                        if (!new TrabajadorInsert().equipos(equipo)) flag = 0;
                                    }
                                }
                                else flag = 0;
                            }
                            else flag = 0;
                        }
                        else flag = 0;

                    }
                    else flag = 0;
                }
                else flag = 2;//Si ya existe el Rut

                return RedirectToAction("Todos");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            if (Session["rol"] != null && (Session["rol"].Equals("admin") || Session["rol"].Equals("izaje")))
            {
                flag = 1;
                if (this.deleteDiretory(id))
                {
                    if (!new TrabajadorDelete().equipos(id)) flag = 0;
                    if (!new TrabajadorDelete().certificados(id)) flag = 0;
                    if (!new TrabajadorDelete().licencias(id)) flag = 0;
                    if (!new TrabajadorDelete().datos(id)) flag = 0;
                }
                else flag = 0;

                return RedirectToAction("Todos");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        private TrabajadorDatos saveDatos(FormCollection form, HttpPostedFileBase imagen){

ProyectoIzaje/WebIzaje/Views/Trabajador/Todos.cshtml
@model IEnumerable<WebIzaje.Models.TrabajadorDatos>
@{
    ViewBag.Title = "Trabajadores";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 10);
}

<div class="container">
    @if (ViewBag.success == 0)
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <strong><i class="glyphicon glyphicon-remove-circle text-danger"></i></strong>&nbsp;No se pudieron realizar los cambios!.
        </div> 
    }
    @if (ViewBag.success == 1)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <strong><i class="glyphicon glyphicon-ok-circle text-success"></i></strong>&nbsp;Cambios realizados con exito!.
        </div>
    }
    @if (ViewBag.success == 2)
    {
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <strong><i class="glyphicon glyphicon-info-sign text-warning"></i></strong>&nbsp;Rut ingresado, ya existe!.
        </div>
    }

    <div class="page-header">
        <h2 class="text-center">Trabajadores</h2>
    </div>
   
    <div class="table-responsive">

        @grid.GetHtml(
            columns: grid.Columns(

        grid.Column("rut",
                 header: string.Format("Rut {0}", grid.SortColumn == "rut" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : ""), style: "text-muted",
            format: @<text>
                <span class="badge">@item.rut</span>
            </text>),
        
        grid.Column("nombre",
            header: string.Format("Nombre {0}", grid.SortColumn == "nombre" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("apellidop",
            header: string.Format("Apellido Paterno {0}", grid.SortColumn == "apellidop" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("apellidom",
            header: string.Format("Apellido Materno {0}", grid.SortColumn == "apellidom" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("fono",
            header: string.Format("Fono {0}", grid.SortColumn == "fono" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),
            
        grid.Column("rol",
            header: string.Format("Rol {0}", grid.SortColumn == "rol" ? grid.SortDirection == SortDirection.Ascending ? "⇈" : "⇊" : "")),

        grid.Column("",
            header: "",
            format: @<text>
                <a href="@Url.Action("Editar", "Trabajador", new { id = @item.rut })" title="Editar"><i class='glyphicon glyphicon-edit text-primary'></i></a>
        &emsp;
                <a href="#" data-toggle="modal" data-target="#myModal" onclick="funcionDelete('@item.rut','@item.nombre')" title="Eliminar"><i class='glyphicon glyphicon-trash text-danger'></i></a>
            </text>)
        ), tableStyle: "table table-hover",footerStyle: "pagination")
    </div>

    <hr />
    <a href="@Url.Action("Nuevo", "Trabajador")" type="button" class="btn btn-default"><i class="glyphicon glyphicon-plus-sign text-success"></i>&nbsp;Nuevo</a>
     

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">¿Eliminar Registro?</h4>
                </div>
                <div class="modal-body">
                    <h5 class="text-center" id="text-modal"></h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i>Cancelar</button>
                    <a href="" type="button" id="btn_delete" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i>Eliminar</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!--CSS StickyFooter-->
<link rel="stylesheet" href="~/Content/bootstrap-stickyfooter.css">
<div class="footer">
    <footer>
        <h5 class="text-muted text-center">
            &copy; <strong>MINDgl</strong> <br />
            <i class="glyphicon glyphicon-map-marker text-muted"></i>&ensp;La Serena, Chile - @DateTime.Now.Year
        </h5>
    </footer>
</div>

@section scripts{
    <script type="text/javascript">

        function funcionDelete(num, name) {
            $("#text-modal").html("");
            var cadena = "@Url.Action("Delete", "Trabajador", new { id = "num"})";
            cadena = cadena.replace("num",num);
            $("#btn_delete").attr("href", cadena);
            $("#text-modal").append("¿Estás seguro de que deseas eliminar a <strong>"+name+"</strong>  de Trabajadores?");

        }

    </script>
}